# Generated by Django 3.2.5 on 2021-07-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_task_piority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='task_group',
            new_name='name',
        ),
    ]
