# Generated by Django 3.2.5 on 2021-07-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='status',
        ),
    ]
